services:
  - type: web
    name: nk-great-global-enterprise
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    previews:
      generation: automatic
    routes:
      - type: rewrite
        source: /admin
        destination: /admin.html
      - type: rewrite
        source: /*
        destination: /index.html
